// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x20000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x21000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  intptr_t res = 0;
  res = syscall(__NR_socket, /*domain=*/0xaul, /*type=*/1ul, /*proto=*/0);
  if (res != -1)
    r[0] = res;
  *(uint8_t*)0x200015c0 = 0xfc;
  *(uint8_t*)0x200015c1 = 2;
  memset((void*)0x200015c2, 0, 13);
  *(uint8_t*)0x200015cf = 1;
  *(uint8_t*)0x200015d0 = 0xfe;
  *(uint8_t*)0x200015d1 = 0x80;
  memset((void*)0x200015d2, 0, 13);
  *(uint8_t*)0x200015df = 0xaa;
  *(uint8_t*)0x200015e0 = 0xfc;
  *(uint8_t*)0x200015e1 = 2;
  memset((void*)0x200015e2, 0, 13);
  *(uint8_t*)0x200015ef = 0;
  *(uint32_t*)0x200015f0 = 5;
  *(uint16_t*)0x200015f4 = 0x401;
  *(uint16_t*)0x200015f6 = 0x8001;
  *(uint32_t*)0x200015f8 = 0x100;
  *(uint64_t*)0x20001600 = 0x80000001;
  *(uint32_t*)0x20001608 = 0;
  *(uint32_t*)0x2000160c = 0;
  syscall(__NR_ioctl, /*fd=*/r[0], /*cmd=*/0x890b, /*arg=*/0x200015c0ul);
  return 0;
}
