// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#ifndef __NR_fsconfig
#define __NR_fsconfig 431
#endif
#ifndef __NR_fsmount
#define __NR_fsmount 432
#endif
#ifndef __NR_fsopen
#define __NR_fsopen 430
#endif
#ifndef __NR_move_mount
#define __NR_move_mount 429
#endif

uint64_t r[3] = {0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffffffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200000000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200001000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  const char* reason;
  (void)reason;
  intptr_t res = 0;
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  memcpy((void*)0x200000000180, "bpf\000", 4);
  res = syscall(__NR_fsopen, /*type=*/0x200000000180ul, /*flags=*/0ul);
  if (res != -1)
    r[0] = res;
  syscall(__NR_fsconfig, /*fd=*/r[0], /*cmd=*/6ul, /*key=*/0ul, /*value=*/0ul,
          /*aux=*/0ul);
  res =
      syscall(__NR_fsmount, /*fs_fd=*/r[0], /*flags=*/0ul, /*attr_flags=*/0ul);
  if (res != -1)
    r[1] = res;
  memcpy((void*)0x200000000040, "./file0\000", 8);
  syscall(__NR_mkdirat, /*fd=*/r[1], /*path=*/0x200000000040ul, /*mode=*/0ul);
  res = syscall(__NR_pipe2, /*pipefd=*/0x200000000000ul, /*flags=*/0ul);
  if (res != -1)
    r[2] = *(uint32_t*)0x200000000004;
  memcpy((void*)0x200000000100, "./file0\000", 8);
  syscall(
      __NR_move_mount, /*from_dfd=*/r[2], /*from_pathname=*/0ul,
      /*to_dfd=*/r[1], /*to_pathname=*/0x200000000100ul,
      /*flags=MOVE_MOUNT_T_AUTOMOUNTS|MOVE_MOUNT_F_EMPTY_PATH|MOVE_MOUNT_F_AUTOMOUNTS*/
      0x26ul);
  return 0;
}
