// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[3] = {0xffffffffffffffff, 0x0, 0x0};

int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x20000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x21000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  intptr_t res = 0;
  memcpy((void*)0x200006c0, "/dev/iommu\000", 11);
  res = syscall(__NR_openat, /*fd=*/0xffffffffffffff9cul, /*file=*/0x200006c0ul,
                /*flags=*/0ul, /*mode=*/0ul);
  if (res != -1)
    r[0] = res;
  *(uint32_t*)0x20000000 = 0xc;
  *(uint32_t*)0x20000004 = 0;
  res = syscall(__NR_ioctl, /*fd=*/r[0], /*cmd=*/0x3b81, /*arg=*/0x20000000ul);
  if (res != -1)
    r[1] = *(uint32_t*)0x20000008;
  *(uint32_t*)0x200001c0 = 0x48;
  *(uint32_t*)0x200001c4 = 2;
  *(uint32_t*)0x200001c8 = r[1];
  *(uint32_t*)0x200001cc = 0;
  *(uint32_t*)0x200001dc = 0;
  res = syscall(__NR_ioctl, /*fd=*/r[0], /*cmd=*/0x3ba0, /*arg=*/0x200001c0ul);
  if (res != -1)
    r[2] = *(uint32_t*)0x200001d0;
  *(uint32_t*)0x20000300 = 0x48;
  *(uint32_t*)0x20000304 = 0x14;
  *(uint32_t*)0x20000308 = r[2];
  *(uint32_t*)0x2000030c = 0;
  *(uint32_t*)0x20000310 = r[1];
  syscall(__NR_ioctl, /*fd=*/r[0], /*cmd=*/0x3ba0, /*arg=*/0x20000300ul);
  return 0;
}
