// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#ifndef __NR_bpf
#define __NR_bpf 321
#endif

#define BITMASK(bf_off, bf_len) (((1ull << (bf_len)) - 1) << (bf_off))
#define STORE_BY_BITMASK(type, htobe, addr, val, bf_off, bf_len)               \
  *(type*)(addr) =                                                             \
      htobe((htobe(*(type*)(addr)) & ~BITMASK((bf_off), (bf_len))) |           \
            (((type)(val) << (bf_off)) & BITMASK((bf_off), (bf_len))))

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=*/0x32ul, /*fd=*/-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x20000000ul, /*len=*/0x1000000ul, /*prot=*/7ul,
          /*flags=*/0x32ul, /*fd=*/-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x21000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=*/0x32ul, /*fd=*/-1, /*offset=*/0ul);
  intptr_t res = 0;
  *(uint32_t*)0x20000100 = 0x1b;
  *(uint32_t*)0x20000104 = 0;
  *(uint32_t*)0x20000108 = 0;
  *(uint32_t*)0x2000010c = 0x8000;
  *(uint32_t*)0x20000110 = 0;
  *(uint32_t*)0x20000114 = -1;
  *(uint32_t*)0x20000118 = 0;
  memset((void*)0x2000011c, 0, 16);
  *(uint32_t*)0x2000012c = 0;
  *(uint32_t*)0x20000130 = -1;
  *(uint32_t*)0x20000134 = 0;
  *(uint32_t*)0x20000138 = 0;
  *(uint32_t*)0x2000013c = 0;
  *(uint64_t*)0x20000140 = 0;
  res = syscall(__NR_bpf, /*cmd=*/0ul, /*arg=*/0x20000100ul, /*size=*/0x48ul);
  if (res != -1)
    r[0] = res;
  *(uint32_t*)0x200014c0 = 0x17;
  *(uint32_t*)0x200014c4 = 0x18;
  *(uint64_t*)0x200014c8 = 0x20000000;
  *(uint8_t*)0x20000000 = 0x18;
  STORE_BY_BITMASK(uint8_t, , 0x20000001, 0, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000001, 0, 4, 4);
  *(uint16_t*)0x20000002 = 0;
  *(uint32_t*)0x20000004 = 0;
  *(uint8_t*)0x20000008 = 0;
  *(uint8_t*)0x20000009 = 0;
  *(uint16_t*)0x2000000a = 0;
  *(uint32_t*)0x2000000c = 0;
  *(uint8_t*)0x20000010 = 0x18;
  STORE_BY_BITMASK(uint8_t, , 0x20000011, 1, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000011, 1, 4, 4);
  *(uint16_t*)0x20000012 = 0;
  *(uint32_t*)0x20000014 = r[0];
  *(uint8_t*)0x20000018 = 0;
  *(uint8_t*)0x20000019 = 0;
  *(uint16_t*)0x2000001a = 0;
  *(uint32_t*)0x2000001c = 0;
  STORE_BY_BITMASK(uint8_t, , 0x20000020, 7, 0, 3);
  STORE_BY_BITMASK(uint8_t, , 0x20000020, 0, 3, 1);
  STORE_BY_BITMASK(uint8_t, , 0x20000020, 0xb, 4, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000021, 2, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000021, 0, 4, 4);
  *(uint16_t*)0x20000022 = 0;
  *(uint32_t*)0x20000024 = 0xf4240;
  STORE_BY_BITMASK(uint8_t, , 0x20000028, 7, 0, 3);
  STORE_BY_BITMASK(uint8_t, , 0x20000028, 0, 3, 1);
  STORE_BY_BITMASK(uint8_t, , 0x20000028, 0xb, 4, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000029, 3, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000029, 0, 4, 4);
  *(uint16_t*)0x2000002a = 0;
  *(uint32_t*)0x2000002c = 0;
  *(uint8_t*)0x20000030 = 0x85;
  *(uint8_t*)0x20000031 = 0;
  *(uint16_t*)0x20000032 = 0;
  *(uint32_t*)0x20000034 = 0xbb;
  STORE_BY_BITMASK(uint8_t, , 0x20000038, 7, 0, 3);
  STORE_BY_BITMASK(uint8_t, , 0x20000038, 1, 3, 1);
  STORE_BY_BITMASK(uint8_t, , 0x20000038, 0xb, 4, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000039, 9, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000039, 0, 4, 4);
  *(uint16_t*)0x2000003a = 0;
  *(uint32_t*)0x2000003c = 0;
  STORE_BY_BITMASK(uint8_t, , 0x20000040, 5, 0, 3);
  STORE_BY_BITMASK(uint8_t, , 0x20000040, 0, 3, 1);
  STORE_BY_BITMASK(uint8_t, , 0x20000040, 6, 4, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000041, 9, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000041, 0, 4, 4);
  *(uint16_t*)0x20000042 = 1;
  *(uint32_t*)0x20000044 = 0;
  *(uint8_t*)0x20000048 = 0xe5;
  *(uint8_t*)0x20000049 = 0;
  *(uint16_t*)0x2000004a = 0;
  *(uint32_t*)0x2000004c = 0;
  *(uint8_t*)0x20000050 = 0x18;
  STORE_BY_BITMASK(uint8_t, , 0x20000051, 1, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000051, 0, 4, 4);
  *(uint16_t*)0x20000052 = 0;
  *(uint32_t*)0x20000054 = -1;
  *(uint8_t*)0x20000058 = 0;
  *(uint8_t*)0x20000059 = 0;
  *(uint16_t*)0x2000005a = 0;
  *(uint32_t*)0x2000005c = 0;
  STORE_BY_BITMASK(uint8_t, , 0x20000060, 7, 0, 3);
  STORE_BY_BITMASK(uint8_t, , 0x20000060, 0, 3, 1);
  STORE_BY_BITMASK(uint8_t, , 0x20000060, 0xb, 4, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000061, 8, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000061, 0, 4, 4);
  *(uint16_t*)0x20000062 = 0;
  *(uint32_t*)0x20000064 = 0;
  STORE_BY_BITMASK(uint8_t, , 0x20000068, 3, 0, 3);
  STORE_BY_BITMASK(uint8_t, , 0x20000068, 3, 3, 2);
  STORE_BY_BITMASK(uint8_t, , 0x20000068, 3, 5, 3);
  STORE_BY_BITMASK(uint8_t, , 0x20000069, 0xa, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000069, 8, 4, 4);
  *(uint16_t*)0x2000006a = 0xfe00;
  *(uint32_t*)0x2000006c = 0;
  STORE_BY_BITMASK(uint8_t, , 0x20000070, 7, 0, 3);
  STORE_BY_BITMASK(uint8_t, , 0x20000070, 1, 3, 1);
  STORE_BY_BITMASK(uint8_t, , 0x20000070, 0xb, 4, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000071, 2, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000071, 9, 4, 4);
  *(uint16_t*)0x20000072 = 0;
  *(uint32_t*)0x20000074 = 0;
  STORE_BY_BITMASK(uint8_t, , 0x20000078, 7, 0, 3);
  STORE_BY_BITMASK(uint8_t, , 0x20000078, 0, 3, 1);
  STORE_BY_BITMASK(uint8_t, , 0x20000078, 2, 4, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000079, 2, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000079, 0, 4, 4);
  *(uint16_t*)0x2000007a = 0;
  *(uint32_t*)0x2000007c = 0xfffffff8;
  STORE_BY_BITMASK(uint8_t, , 0x20000080, 7, 0, 3);
  STORE_BY_BITMASK(uint8_t, , 0x20000080, 0, 3, 1);
  STORE_BY_BITMASK(uint8_t, , 0x20000080, 0xb, 4, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000081, 3, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000081, 0, 4, 4);
  *(uint16_t*)0x20000082 = 0;
  *(uint32_t*)0x20000084 = 8;
  STORE_BY_BITMASK(uint8_t, , 0x20000088, 7, 0, 3);
  STORE_BY_BITMASK(uint8_t, , 0x20000088, 0, 3, 1);
  STORE_BY_BITMASK(uint8_t, , 0x20000088, 0xb, 4, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000089, 4, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000089, 0, 4, 4);
  *(uint16_t*)0x2000008a = 0;
  *(uint32_t*)0x2000008c = 0;
  *(uint8_t*)0x20000090 = 7;
  *(uint8_t*)0x20000091 = 0;
  *(uint16_t*)0x20000092 = 0;
  *(uint32_t*)0x20000094 = 0x82;
  STORE_BY_BITMASK(uint8_t, , 0x20000098, 6, 0, 3);
  STORE_BY_BITMASK(uint8_t, , 0x20000098, 1, 3, 1);
  STORE_BY_BITMASK(uint8_t, , 0x20000098, 0xb, 4, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000099, 2, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000099, 9, 4, 4);
  *(uint16_t*)0x2000009a = 0;
  *(uint32_t*)0x2000009c = 0;
  STORE_BY_BITMASK(uint8_t, , 0x200000a0, 5, 0, 3);
  STORE_BY_BITMASK(uint8_t, , 0x200000a0, 0, 3, 1);
  STORE_BY_BITMASK(uint8_t, , 0x200000a0, 0xb, 4, 4);
  STORE_BY_BITMASK(uint8_t, , 0x200000a1, 2, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x200000a1, 0, 4, 4);
  *(uint16_t*)0x200000a2 = 0;
  *(uint32_t*)0x200000a4 = 2;
  *(uint8_t*)0x200000a8 = 0x4e;
  *(uint8_t*)0x200000a9 = 0;
  *(uint16_t*)0x200000aa = 0;
  *(uint32_t*)0x200000ac = 0;
  STORE_BY_BITMASK(uint8_t, , 0x200000b0, 7, 0, 3);
  STORE_BY_BITMASK(uint8_t, , 0x200000b0, 0, 3, 1);
  STORE_BY_BITMASK(uint8_t, , 0x200000b0, 0xb, 4, 4);
  STORE_BY_BITMASK(uint8_t, , 0x200000b1, 0, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x200000b1, 0, 4, 4);
  *(uint16_t*)0x200000b2 = 0;
  *(uint32_t*)0x200000b4 = 0;
  *(uint8_t*)0x200000b8 = 0x95;
  *(uint8_t*)0x200000b9 = 0;
  *(uint16_t*)0x200000ba = 0;
  *(uint32_t*)0x200000bc = 0;
  *(uint64_t*)0x200014d0 = 0x200000c0;
  memcpy((void*)0x200000c0, "syzkaller\000", 10);
  *(uint32_t*)0x200014d8 = 0;
  *(uint32_t*)0x200014dc = 0;
  *(uint64_t*)0x200014e0 = 0;
  *(uint32_t*)0x200014e8 = 0;
  *(uint32_t*)0x200014ec = 0;
  memset((void*)0x200014f0, 0, 16);
  *(uint32_t*)0x20001500 = 0;
  *(uint32_t*)0x20001504 = 0x25;
  *(uint32_t*)0x20001508 = -1;
  *(uint32_t*)0x2000150c = 8;
  *(uint64_t*)0x20001510 = 0;
  *(uint32_t*)0x20001518 = 0;
  *(uint32_t*)0x2000151c = 0x10;
  *(uint64_t*)0x20001520 = 0;
  *(uint32_t*)0x20001528 = 0;
  *(uint32_t*)0x2000152c = 0;
  *(uint32_t*)0x20001530 = 0;
  *(uint32_t*)0x20001534 = 0;
  *(uint64_t*)0x20001538 = 0;
  *(uint64_t*)0x20001540 = 0;
  *(uint32_t*)0x20001548 = 0x10;
  *(uint32_t*)0x2000154c = 0;
  syscall(__NR_bpf, /*cmd=*/5ul, /*arg=*/0x200014c0ul, /*size=*/0x90ul);
  return 0;
}
