// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffffffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200000000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200001000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  const char* reason;
  (void)reason;
  intptr_t res = 0;
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  //  unshare arguments: [
  //    flags: unshare_flags = 0x40000600 (8 bytes)
  //  ]
  syscall(__NR_unshare,
          /*flags=CLONE_NEWNET|CLONE_FS|CLONE_FILES*/ 0x40000600ul);
  //  socket$igmp arguments: [
  //    domain: const = 0x2 (8 bytes)
  //    type: const = 0x3 (8 bytes)
  //    proto: const = 0x2 (4 bytes)
  //  ]
  //  returns sock_igmp
  res = syscall(__NR_socket, /*domain=*/2ul, /*type=*/3ul, /*proto=*/2);
  if (res != -1)
    r[0] = res;
  //  setsockopt$MRT_ADD_VIF arguments: [
  //    fd: sock_igmp (resource)
  //    level: const = 0x0 (4 bytes)
  //    opt: const = 0xca (4 bytes)
  //    val: ptr[in, vifctl] {
  //      vifctl {
  //        vifc_vifi: int16 = 0x0 (2 bytes)
  //        vifc_flags: viff_ctls = 0x4 (1 bytes)
  //        vifc_threshold: int8 = 0x0 (1 bytes)
  //        vifc_rate_limit: int32 = 0x0 (4 bytes)
  //        u: union vifctl_u {
  //          vifc_lcl_addr: union ipv4_addr {
  //            loopback: const = 0x7f000001 (4 bytes)
  //          }
  //        }
  //        vifc_rmt_addr: union ipv4_addr {
  //          multicast1: const = 0xe0000001 (4 bytes)
  //        }
  //      }
  //    }
  //    len: bytesize = 0x10 (8 bytes)
  //  ]
  *(uint16_t*)0x200000000400 = 0;
  *(uint8_t*)0x200000000402 = 4;
  *(uint8_t*)0x200000000403 = 0;
  *(uint32_t*)0x200000000404 = 0;
  *(uint32_t*)0x200000000408 = htobe32(0x7f000001);
  *(uint32_t*)0x20000000040c = htobe32(0xe0000001);
  syscall(__NR_setsockopt, /*fd=*/r[0], /*level=*/0, /*opt=*/0xca,
          /*val=*/0x200000000400ul, /*len=*/0x10ul);
  //  socket$packet arguments: [
  //    domain: const = 0x11 (8 bytes)
  //    type: packet_socket_type = 0x3 (8 bytes)
  //    proto: const = 0x300 (4 bytes)
  //  ]
  //  returns sock_packet
  res = syscall(__NR_socket, /*domain=*/0x11ul, /*type=SOCK_RAW*/ 3ul,
                /*proto=*/0x300);
  if (res != -1)
    r[1] = res;
  //  sendmsg arguments: [
  //    fd: sock (resource)
  //    msg: ptr[in, send_msghdr] {
  //      send_msghdr {
  //        msg_name: ptr[in, sockaddr_storage] {
  //          union sockaddr_storage {
  //            phonet: sockaddr_pn {
  //              spn_family: const = 0x23 (2 bytes)
  //              spn_obj: int8 = 0x0 (1 bytes)
  //              spn_dev: int8 = 0x0 (1 bytes)
  //              spn_resource: int8 = 0x2 (1 bytes)
  //              spn_zero: buffer: {00 00 00 00 00 00 00 00 00 00 00} (length
  //              0xb)
  //            }
  //          }
  //        }
  //        msg_namelen: len = 0x80 (4 bytes)
  //        pad = 0x0 (4 bytes)
  //        msg_iov: ptr[in, array[iovec[in, array[int8]]]] {
  //          array[iovec[in, array[int8]]] {
  //            iovec[in, array[int8]] {
  //              addr: ptr[in, buffer] {
  //                buffer: {9a 79 a6 68} (length 0x4)
  //              }
  //              len: len = 0x4 (8 bytes)
  //            }
  //          }
  //        }
  //        msg_iovlen: len = 0x1 (8 bytes)
  //        msg_control: nil
  //        msg_controllen: bytesize = 0x0 (8 bytes)
  //        msg_flags: const = 0x0 (4 bytes)
  //        pad = 0x0 (4 bytes)
  //      }
  //    }
  //    f: send_flags = 0x0 (8 bytes)
  //  ]
  *(uint64_t*)0x2000000012c0 = 0x200000000300;
  *(uint16_t*)0x200000000300 = 0x23;
  *(uint8_t*)0x200000000302 = 0;
  *(uint8_t*)0x200000000303 = 0;
  *(uint8_t*)0x200000000304 = 2;
  memset((void*)0x200000000305, 0, 11);
  *(uint32_t*)0x2000000012c8 = 0x80;
  *(uint64_t*)0x2000000012d0 = 0x200000000380;
  *(uint64_t*)0x200000000380 = 0x2000000000c0;
  memcpy((void*)0x2000000000c0, "\x9a\x79\xa6\x68", 4);
  *(uint64_t*)0x200000000388 = 4;
  *(uint64_t*)0x2000000012d8 = 1;
  *(uint64_t*)0x2000000012e0 = 0;
  *(uint64_t*)0x2000000012e8 = 0;
  *(uint32_t*)0x2000000012f0 = 0;
  syscall(__NR_sendmsg, /*fd=*/r[1], /*msg=*/0x2000000012c0ul, /*f=*/0ul);
  return 0;
}
