// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <dirent.h>
#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <setjmp.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <sys/mount.h>
#include <sys/prctl.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

#include <linux/loop.h>

#ifndef __NR_memfd_create
#define __NR_memfd_create 319
#endif

static unsigned long long procid;

static __thread int clone_ongoing;
static __thread int skip_segv;
static __thread jmp_buf segv_env;

static void segv_handler(int sig, siginfo_t* info, void* ctx)
{
  if (__atomic_load_n(&clone_ongoing, __ATOMIC_RELAXED) != 0) {
    exit(sig);
  }
  uintptr_t addr = (uintptr_t)info->si_addr;
  const uintptr_t prog_start = 1 << 20;
  const uintptr_t prog_end = 100 << 20;
  int skip = __atomic_load_n(&skip_segv, __ATOMIC_RELAXED) != 0;
  int valid = addr < prog_start || addr > prog_end;
  if (skip && valid) {
    _longjmp(segv_env, 1);
  }
  exit(sig);
}

static void install_segv_handler(void)
{
  struct sigaction sa;
  memset(&sa, 0, sizeof(sa));
  sa.sa_handler = SIG_IGN;
  syscall(SYS_rt_sigaction, 0x20, &sa, NULL, 8);
  syscall(SYS_rt_sigaction, 0x21, &sa, NULL, 8);
  memset(&sa, 0, sizeof(sa));
  sa.sa_sigaction = segv_handler;
  sa.sa_flags = SA_NODEFER | SA_SIGINFO;
  sigaction(SIGSEGV, &sa, NULL);
  sigaction(SIGBUS, &sa, NULL);
}

#define NONFAILING(...)                                                        \
  ({                                                                           \
    int ok = 1;                                                                \
    __atomic_fetch_add(&skip_segv, 1, __ATOMIC_SEQ_CST);                       \
    if (_setjmp(segv_env) == 0) {                                              \
      __VA_ARGS__;                                                             \
    } else                                                                     \
      ok = 0;                                                                  \
    __atomic_fetch_sub(&skip_segv, 1, __ATOMIC_SEQ_CST);                       \
    ok;                                                                        \
  })

static void sleep_ms(uint64_t ms)
{
  usleep(ms * 1000);
}

static uint64_t current_time_ms(void)
{
  struct timespec ts;
  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    exit(1);
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

static bool write_file(const char* file, const char* what, ...)
{
  char buf[1024];
  va_list args;
  va_start(args, what);
  vsnprintf(buf, sizeof(buf), what, args);
  va_end(args);
  buf[sizeof(buf) - 1] = 0;
  int len = strlen(buf);
  int fd = open(file, O_WRONLY | O_CLOEXEC);
  if (fd == -1)
    return false;
  if (write(fd, buf, len) != len) {
    int err = errno;
    close(fd);
    errno = err;
    return false;
  }
  close(fd);
  return true;
}

//% This code is derived from puff.{c,h}, found in the zlib development. The
//% original files come with the following copyright notice:

//% Copyright (C) 2002-2013 Mark Adler, all rights reserved
//% version 2.3, 21 Jan 2013
//% This software is provided 'as-is', without any express or implied
//% warranty.  In no event will the author be held liable for any damages
//% arising from the use of this software.
//% Permission is granted to anyone to use this software for any purpose,
//% including commercial applications, and to alter it and redistribute it
//% freely, subject to the following restrictions:
//% 1. The origin of this software must not be misrepresented; you must not
//%    claim that you wrote the original software. If you use this software
//%    in a product, an acknowledgment in the product documentation would be
//%    appreciated but is not required.
//% 2. Altered source versions must be plainly marked as such, and must not be
//%    misrepresented as being the original software.
//% 3. This notice may not be removed or altered from any source distribution.
//% Mark Adler    madler@alumni.caltech.edu

//% BEGIN CODE DERIVED FROM puff.{c,h}

#define MAXBITS 15
#define MAXLCODES 286
#define MAXDCODES 30
#define MAXCODES (MAXLCODES + MAXDCODES)
#define FIXLCODES 288

struct puff_state {
  unsigned char* out;
  unsigned long outlen;
  unsigned long outcnt;
  const unsigned char* in;
  unsigned long inlen;
  unsigned long incnt;
  int bitbuf;
  int bitcnt;
  jmp_buf env;
};
static int puff_bits(struct puff_state* s, int need)
{
  long val = s->bitbuf;
  while (s->bitcnt < need) {
    if (s->incnt == s->inlen)
      longjmp(s->env, 1);
    val |= (long)(s->in[s->incnt++]) << s->bitcnt;
    s->bitcnt += 8;
  }
  s->bitbuf = (int)(val >> need);
  s->bitcnt -= need;
  return (int)(val & ((1L << need) - 1));
}
static int puff_stored(struct puff_state* s)
{
  s->bitbuf = 0;
  s->bitcnt = 0;
  if (s->incnt + 4 > s->inlen)
    return 2;
  unsigned len = s->in[s->incnt++];
  len |= s->in[s->incnt++] << 8;
  if (s->in[s->incnt++] != (~len & 0xff) ||
      s->in[s->incnt++] != ((~len >> 8) & 0xff))
    return -2;
  if (s->incnt + len > s->inlen)
    return 2;
  if (s->outcnt + len > s->outlen)
    return 1;
  for (; len--; s->outcnt++, s->incnt++) {
    if (s->in[s->incnt])
      s->out[s->outcnt] = s->in[s->incnt];
  }
  return 0;
}
struct puff_huffman {
  short* count;
  short* symbol;
};
static int puff_decode(struct puff_state* s, const struct puff_huffman* h)
{
  int first = 0;
  int index = 0;
  int bitbuf = s->bitbuf;
  int left = s->bitcnt;
  int code = first = index = 0;
  int len = 1;
  short* next = h->count + 1;
  while (1) {
    while (left--) {
      code |= bitbuf & 1;
      bitbuf >>= 1;
      int count = *next++;
      if (code - count < first) {
        s->bitbuf = bitbuf;
        s->bitcnt = (s->bitcnt - len) & 7;
        return h->symbol[index + (code - first)];
      }
      index += count;
      first += count;
      first <<= 1;
      code <<= 1;
      len++;
    }
    left = (MAXBITS + 1) - len;
    if (left == 0)
      break;
    if (s->incnt == s->inlen)
      longjmp(s->env, 1);
    bitbuf = s->in[s->incnt++];
    if (left > 8)
      left = 8;
  }
  return -10;
}
static int puff_construct(struct puff_huffman* h, const short* length, int n)
{
  int len;
  for (len = 0; len <= MAXBITS; len++)
    h->count[len] = 0;
  int symbol;
  for (symbol = 0; symbol < n; symbol++)
    (h->count[length[symbol]])++;
  if (h->count[0] == n)
    return 0;
  int left = 1;
  for (len = 1; len <= MAXBITS; len++) {
    left <<= 1;
    left -= h->count[len];
    if (left < 0)
      return left;
  }
  short offs[MAXBITS + 1];
  offs[1] = 0;
  for (len = 1; len < MAXBITS; len++)
    offs[len + 1] = offs[len] + h->count[len];
  for (symbol = 0; symbol < n; symbol++)
    if (length[symbol] != 0)
      h->symbol[offs[length[symbol]]++] = symbol;
  return left;
}
static int puff_codes(struct puff_state* s, const struct puff_huffman* lencode,
                      const struct puff_huffman* distcode)
{
  static const short lens[29] = {3,  4,  5,  6,   7,   8,   9,   10,  11, 13,
                                 15, 17, 19, 23,  27,  31,  35,  43,  51, 59,
                                 67, 83, 99, 115, 131, 163, 195, 227, 258};
  static const short lext[29] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2,
                                 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 0};
  static const short dists[30] = {
      1,    2,    3,    4,    5,    7,    9,    13,    17,    25,
      33,   49,   65,   97,   129,  193,  257,  385,   513,   769,
      1025, 1537, 2049, 3073, 4097, 6145, 8193, 12289, 16385, 24577};
  static const short dext[30] = {0, 0, 0,  0,  1,  1,  2,  2,  3,  3,
                                 4, 4, 5,  5,  6,  6,  7,  7,  8,  8,
                                 9, 9, 10, 10, 11, 11, 12, 12, 13, 13};
  int symbol;
  do {
    symbol = puff_decode(s, lencode);
    if (symbol < 0)
      return symbol;
    if (symbol < 256) {
      if (s->outcnt == s->outlen)
        return 1;
      if (symbol)
        s->out[s->outcnt] = symbol;
      s->outcnt++;
    } else if (symbol > 256) {
      symbol -= 257;
      if (symbol >= 29)
        return -10;
      int len = lens[symbol] + puff_bits(s, lext[symbol]);
      symbol = puff_decode(s, distcode);
      if (symbol < 0)
        return symbol;
      unsigned dist = dists[symbol] + puff_bits(s, dext[symbol]);
      if (dist > s->outcnt)
        return -11;
      if (s->outcnt + len > s->outlen)
        return 1;
      while (len--) {
        if (dist <= s->outcnt && s->out[s->outcnt - dist])
          s->out[s->outcnt] = s->out[s->outcnt - dist];
        s->outcnt++;
      }
    }
  } while (symbol != 256);
  return 0;
}
static int puff_fixed(struct puff_state* s)
{
  static int virgin = 1;
  static short lencnt[MAXBITS + 1], lensym[FIXLCODES];
  static short distcnt[MAXBITS + 1], distsym[MAXDCODES];
  static struct puff_huffman lencode, distcode;
  if (virgin) {
    lencode.count = lencnt;
    lencode.symbol = lensym;
    distcode.count = distcnt;
    distcode.symbol = distsym;
    short lengths[FIXLCODES];
    int symbol;
    for (symbol = 0; symbol < 144; symbol++)
      lengths[symbol] = 8;
    for (; symbol < 256; symbol++)
      lengths[symbol] = 9;
    for (; symbol < 280; symbol++)
      lengths[symbol] = 7;
    for (; symbol < FIXLCODES; symbol++)
      lengths[symbol] = 8;
    puff_construct(&lencode, lengths, FIXLCODES);
    for (symbol = 0; symbol < MAXDCODES; symbol++)
      lengths[symbol] = 5;
    puff_construct(&distcode, lengths, MAXDCODES);
    virgin = 0;
  }
  return puff_codes(s, &lencode, &distcode);
}
static int puff_dynamic(struct puff_state* s)
{
  static const short order[19] = {16, 17, 18, 0, 8,  7, 9,  6, 10, 5,
                                  11, 4,  12, 3, 13, 2, 14, 1, 15};
  int nlen = puff_bits(s, 5) + 257;
  int ndist = puff_bits(s, 5) + 1;
  int ncode = puff_bits(s, 4) + 4;
  if (nlen > MAXLCODES || ndist > MAXDCODES)
    return -3;
  short lengths[MAXCODES];
  int index;
  for (index = 0; index < ncode; index++)
    lengths[order[index]] = puff_bits(s, 3);
  for (; index < 19; index++)
    lengths[order[index]] = 0;
  short lencnt[MAXBITS + 1], lensym[MAXLCODES];
  struct puff_huffman lencode = {lencnt, lensym};
  int err = puff_construct(&lencode, lengths, 19);
  if (err != 0)
    return -4;
  index = 0;
  while (index < nlen + ndist) {
    int symbol;
    int len;
    symbol = puff_decode(s, &lencode);
    if (symbol < 0)
      return symbol;
    if (symbol < 16)
      lengths[index++] = symbol;
    else {
      len = 0;
      if (symbol == 16) {
        if (index == 0)
          return -5;
        len = lengths[index - 1];
        symbol = 3 + puff_bits(s, 2);
      } else if (symbol == 17)
        symbol = 3 + puff_bits(s, 3);
      else
        symbol = 11 + puff_bits(s, 7);
      if (index + symbol > nlen + ndist)
        return -6;
      while (symbol--)
        lengths[index++] = len;
    }
  }
  if (lengths[256] == 0)
    return -9;
  err = puff_construct(&lencode, lengths, nlen);
  if (err && (err < 0 || nlen != lencode.count[0] + lencode.count[1]))
    return -7;
  short distcnt[MAXBITS + 1], distsym[MAXDCODES];
  struct puff_huffman distcode = {distcnt, distsym};
  err = puff_construct(&distcode, lengths + nlen, ndist);
  if (err && (err < 0 || ndist != distcode.count[0] + distcode.count[1]))
    return -8;
  return puff_codes(s, &lencode, &distcode);
}
static int puff(unsigned char* dest, unsigned long* destlen,
                const unsigned char* source, unsigned long sourcelen)
{
  struct puff_state s = {
      .out = dest,
      .outlen = *destlen,
      .outcnt = 0,
      .in = source,
      .inlen = sourcelen,
      .incnt = 0,
      .bitbuf = 0,
      .bitcnt = 0,
  };
  int err;
  if (setjmp(s.env) != 0)
    err = 2;
  else {
    int last;
    do {
      last = puff_bits(&s, 1);
      int type = puff_bits(&s, 2);
      err = type == 0 ? puff_stored(&s)
                      : (type == 1 ? puff_fixed(&s)
                                   : (type == 2 ? puff_dynamic(&s) : -1));
      if (err != 0)
        break;
    } while (!last);
  }
  *destlen = s.outcnt;
  return err;
}

//% END CODE DERIVED FROM puff.{c,h}

#define ZLIB_HEADER_WIDTH 2

static int puff_zlib_to_file(const unsigned char* source,
                             unsigned long sourcelen, int dest_fd)
{
  if (sourcelen < ZLIB_HEADER_WIDTH)
    return 0;
  source += ZLIB_HEADER_WIDTH;
  sourcelen -= ZLIB_HEADER_WIDTH;
  const unsigned long max_destlen = 132 << 20;
  void* ret = mmap(0, max_destlen, PROT_WRITE | PROT_READ,
                   MAP_PRIVATE | MAP_ANON, -1, 0);
  if (ret == MAP_FAILED)
    return -1;
  unsigned char* dest = (unsigned char*)ret;
  unsigned long destlen = max_destlen;
  int err = puff(dest, &destlen, source, sourcelen);
  if (err) {
    munmap(dest, max_destlen);
    errno = -err;
    return -1;
  }
  if (write(dest_fd, dest, destlen) != (ssize_t)destlen) {
    munmap(dest, max_destlen);
    return -1;
  }
  return munmap(dest, max_destlen);
}

static int setup_loop_device(unsigned char* data, unsigned long size,
                             const char* loopname, int* loopfd_p)
{
  int err = 0, loopfd = -1;
  int memfd = syscall(__NR_memfd_create, "syzkaller", 0);
  if (memfd == -1) {
    err = errno;
    goto error;
  }
  if (puff_zlib_to_file(data, size, memfd)) {
    err = errno;
    goto error_close_memfd;
  }
  loopfd = open(loopname, O_RDWR);
  if (loopfd == -1) {
    err = errno;
    goto error_close_memfd;
  }
  if (ioctl(loopfd, LOOP_SET_FD, memfd)) {
    if (errno != EBUSY) {
      err = errno;
      goto error_close_loop;
    }
    ioctl(loopfd, LOOP_CLR_FD, 0);
    usleep(1000);
    if (ioctl(loopfd, LOOP_SET_FD, memfd)) {
      err = errno;
      goto error_close_loop;
    }
  }
  close(memfd);
  *loopfd_p = loopfd;
  return 0;

error_close_loop:
  close(loopfd);
error_close_memfd:
  close(memfd);
error:
  errno = err;
  return -1;
}

static void reset_loop_device(const char* loopname)
{
  int loopfd = open(loopname, O_RDWR);
  if (loopfd == -1) {
    return;
  }
  if (ioctl(loopfd, LOOP_CLR_FD, 0)) {
  }
  close(loopfd);
}

static long syz_mount_image(volatile long fsarg, volatile long dir,
                            volatile long flags, volatile long optsarg,
                            volatile long change_dir,
                            volatile unsigned long size, volatile long image)
{
  unsigned char* data = (unsigned char*)image;
  int res = -1, err = 0, need_loop_device = !!size;
  char* mount_opts = (char*)optsarg;
  char* target = (char*)dir;
  char* fs = (char*)fsarg;
  char* source = NULL;
  char loopname[64];
  if (need_loop_device) {
    int loopfd;
    memset(loopname, 0, sizeof(loopname));
    snprintf(loopname, sizeof(loopname), "/dev/loop%llu", procid);
    if (setup_loop_device(data, size, loopname, &loopfd) == -1)
      return -1;
    close(loopfd);
    source = loopname;
  }
  mkdir(target, 0777);
  char opts[256];
  memset(opts, 0, sizeof(opts));
  if (strlen(mount_opts) > (sizeof(opts) - 32)) {
  }
  strncpy(opts, mount_opts, sizeof(opts) - 32);
  if (strcmp(fs, "iso9660") == 0) {
    flags |= MS_RDONLY;
  } else if (strncmp(fs, "ext", 3) == 0) {
    bool has_remount_ro = false;
    char* remount_ro_start = strstr(opts, "errors=remount-ro");
    if (remount_ro_start != NULL) {
      char after = *(remount_ro_start + strlen("errors=remount-ro"));
      char before = remount_ro_start == opts ? '\0' : *(remount_ro_start - 1);
      has_remount_ro = ((before == '\0' || before == ',') &&
                        (after == '\0' || after == ','));
    }
    if (strstr(opts, "errors=panic") || !has_remount_ro)
      strcat(opts, ",errors=continue");
  } else if (strcmp(fs, "xfs") == 0) {
    strcat(opts, ",nouuid");
  }
  res = mount(source, target, fs, flags, opts);
  if (res == -1) {
    err = errno;
    goto error_clear_loop;
  }
  res = open(target, O_RDONLY | O_DIRECTORY);
  if (res == -1) {
    err = errno;
    goto error_clear_loop;
  }
  if (change_dir) {
    res = chdir(target);
    if (res == -1) {
      err = errno;
    }
  }

error_clear_loop:
  if (need_loop_device)
    reset_loop_device(loopname);
  errno = err;
  return res;
}

static void kill_and_wait(int pid, int* status)
{
  kill(-pid, SIGKILL);
  kill(pid, SIGKILL);
  for (int i = 0; i < 100; i++) {
    if (waitpid(-1, status, WNOHANG | __WALL) == pid)
      return;
    usleep(1000);
  }
  DIR* dir = opendir("/sys/fs/fuse/connections");
  if (dir) {
    for (;;) {
      struct dirent* ent = readdir(dir);
      if (!ent)
        break;
      if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0)
        continue;
      char abort[300];
      snprintf(abort, sizeof(abort), "/sys/fs/fuse/connections/%s/abort",
               ent->d_name);
      int fd = open(abort, O_WRONLY);
      if (fd == -1) {
        continue;
      }
      if (write(fd, abort, 1) < 0) {
      }
      close(fd);
    }
    closedir(dir);
  } else {
  }
  while (waitpid(-1, status, __WALL) != pid) {
  }
}

static void reset_loop()
{
  char buf[64];
  snprintf(buf, sizeof(buf), "/dev/loop%llu", procid);
  int loopfd = open(buf, O_RDWR);
  if (loopfd != -1) {
    ioctl(loopfd, LOOP_CLR_FD, 0);
    close(loopfd);
  }
}

static void setup_test()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  setpgrp();
  write_file("/proc/self/oom_score_adj", "1000");
}

static void execute_one(void);

#define WAIT_FLAGS __WALL

static void loop(void)
{
  int iter = 0;
  for (;; iter++) {
    reset_loop();
    int pid = fork();
    if (pid < 0)
      exit(1);
    if (pid == 0) {
      setup_test();
      execute_one();
      exit(0);
    }
    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      sleep_ms(10);
      if (waitpid(-1, &status, WNOHANG | WAIT_FLAGS) == pid)
        break;
      if (current_time_ms() - start < 5000)
        continue;
      kill_and_wait(pid, &status);
      break;
    }
  }
}

void execute_one(void)
{
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  NONFAILING(memcpy((void*)0x20000100, "./file1\000", 8));
  NONFAILING(syz_mount_image(/*fs=*/0, /*dir=*/0x20000100, /*flags=*/0,
                             /*opts=*/0, /*chdir=*/0, /*size=*/0, /*img=*/0));
  NONFAILING(memcpy((void*)0x20000040, "./file1\000", 8));
  NONFAILING(memcpy((void*)0x20000080, "./file1\000", 8));
  syscall(__NR_mount, /*src=*/0x20000040ul, /*dst=*/0x20000080ul, /*type=*/0ul,
          /*flags=MS_NOATIME|MS_BIND*/ 0x1400ul, /*data=*/0ul);
  NONFAILING(memcpy((void*)0x200002c0, "ext2\000", 5));
  NONFAILING(memcpy((void*)0x200000c0, "./file1\000", 8));
  NONFAILING(memcpy((void*)0x20000300, "sb", 2));
  NONFAILING(*(uint8_t*)0x20000302 = 0x3d);
  NONFAILING(sprintf((char*)0x20000303, "0x%016llx", (long long)0x874e));
  NONFAILING(*(uint8_t*)0x20000315 = 0x2c);
  NONFAILING(memcpy((void*)0x20000316, "journal_checksum", 16));
  NONFAILING(*(uint8_t*)0x20000326 = 0x2c);
  NONFAILING(memcpy((void*)0x20000327, "nogrpid", 7));
  NONFAILING(*(uint8_t*)0x2000032e = 0x2c);
  NONFAILING(memcpy((void*)0x2000032f, "stripe", 6));
  NONFAILING(*(uint8_t*)0x20000335 = 0x3d);
  NONFAILING(sprintf((char*)0x20000336, "0x%016llx", (long long)0xfffffd));
  NONFAILING(*(uint8_t*)0x20000348 = 0x2c);
  NONFAILING(memcpy((void*)0x20000349, "nojournal_checksum", 18));
  NONFAILING(*(uint8_t*)0x2000035b = 0x2c);
  NONFAILING(memcpy((void*)0x2000035c, "quota", 5));
  NONFAILING(*(uint8_t*)0x20000361 = 0x2c);
  NONFAILING(memcpy((void*)0x20000362, "resuid", 6));
  NONFAILING(*(uint8_t*)0x20000368 = 0x3d);
  NONFAILING(sprintf((char*)0x20000369, "0x%016llx", (long long)0));
  NONFAILING(*(uint8_t*)0x2000037b = 0x2c);
  NONFAILING(memcpy((void*)0x2000037c, "init_itable", 11));
  NONFAILING(*(uint8_t*)0x20000387 = 0x2c);
  NONFAILING(memcpy((void*)0x20000388, "usrjquota=", 10));
  NONFAILING(*(uint8_t*)0x20000392 = 0x2c);
  NONFAILING(memcpy((void*)0x20000393, "barrier", 7));
  NONFAILING(*(uint8_t*)0x2000039a = 0x2c);
  NONFAILING(memcpy((void*)0x2000039b, "sb", 2));
  NONFAILING(*(uint8_t*)0x2000039d = 0x3d);
  NONFAILING(sprintf((char*)0x2000039e, "0x%016llx", (long long)0x97));
  NONFAILING(*(uint8_t*)0x200003b0 = 0x2c);
  NONFAILING(memcpy((void*)0x200003b1, "dioread_nolock", 14));
  NONFAILING(*(uint8_t*)0x200003bf = 0x2c);
  NONFAILING(memcpy((void*)0x200003c0, "oldalloc", 8));
  NONFAILING(*(uint8_t*)0x200003c8 = 0x2c);
  NONFAILING(memcpy((void*)0x200003c9, "nodelalloc", 10));
  NONFAILING(*(uint8_t*)0x200003d3 = 0x2c);
  NONFAILING(memcpy((void*)0x200003d4, "data=ordered", 12));
  NONFAILING(*(uint8_t*)0x200003e0 = 0x2c);
  NONFAILING(memcpy((void*)0x200003e1, "grpid", 5));
  NONFAILING(*(uint8_t*)0x200003e6 = 0x2c);
  NONFAILING(memcpy((void*)0x200003e7, "data_err=abort", 14));
  NONFAILING(*(uint8_t*)0x200003f5 = 0x2c);
  NONFAILING(memcpy((void*)0x200003f6, "stripe", 6));
  NONFAILING(*(uint8_t*)0x200003fc = 0x3d);
  NONFAILING(sprintf((char*)0x200003fd, "0x%016llx", (long long)0x100));
  NONFAILING(*(uint8_t*)0x2000040f = 0x2c);
  NONFAILING(memcpy((void*)0x20000410, "subj_user", 9));
  NONFAILING(*(uint8_t*)0x20000419 = 0x3d);
  NONFAILING(memcpy((void*)0x2000041a, "journal_checksum", 16));
  NONFAILING(*(uint8_t*)0x2000042a = 0x2c);
  NONFAILING(memcpy((void*)0x2000042b, "defcontext", 10));
  NONFAILING(*(uint8_t*)0x20000435 = 0x3d);
  NONFAILING(memcpy((void*)0x20000436, "system_u", 8));
  NONFAILING(*(uint8_t*)0x2000043e = 0x2c);
  NONFAILING(memcpy((void*)0x2000043f, "appraise", 8));
  NONFAILING(*(uint8_t*)0x20000447 = 0x2c);
  NONFAILING(memcpy((void*)0x20000448, "audit", 5));
  NONFAILING(*(uint8_t*)0x2000044d = 0x2c);
  NONFAILING(*(uint8_t*)0x2000044e = 0);
  NONFAILING(memcpy(
      (void*)0x20001080,
      "\x78\x9c\xec\xdd\xdf\x6b\x63\x59\x1d\x00\xf0\x6f\x6e\xdb\x69\x67\xb6\x63"
      "\x67\x75\x1f\x56\x5f\x76\xc4\xd5\x11\x96\x49\xa7\x53\x96\x76\xf4\x65\x15"
      "\x61\x05\x59\x50\xe7\x51\xa1\xd6\x36\x2d\xa5\x49\x33\x34\xe9\x3a\x2d\x0b"
      "\xdb\x79\x17\x9f\x04\x57\x45\x50\x1f\x7c\x50\x10\x04\x1f\x15\xfb\x07\xf8"
      "\x28\xf8\xe3\x59\x7d\x10\x44\x67\xea\x83\x28\x78\xe5\x26\x37\x6d\xb6\x4d"
      "\xfa\x6b\x9b\x84\x6d\x3e\x1f\x38\x93\x7b\xee\x49\xf2\x3d\x27\xed\x3d\xe7"
      "\xde\x93\xe9\x3d\x01\x0c\xad\xdb\x11\xb1\x1b\x11\xd7\x22\xe2\x6b\x11\x31"
      "\x95\xef\x2f\xe4\x29\x5e\x6b\xa6\xec\x79\xfb\x4f\x47\xf3\xd2\x34\x7d\xf8"
      "\x8f\x42\xa3\xfc\xd9\xd3\xb7\x96\xa2\xed\x35\x99\xe7\xda\xde\xf3\xcb\xaf"
      "\x47\x7c\xbd\x70\x3c\x6e\x6d\x7b\x67\x7d\xb1\x5c\x2e\x6d\xe6\xf9\xe9\x7a"
      "\xe5\xd1\x74\x6d\x7b\xe7\xee\x5a\x65\x71\xb5\xb4\x5a\xda\x98\x99\x7b\x75"
      "\x76\x7e\x7e\xee\xc1\xfc\xec\x29\x2d\x18\x39\x73\x5b\x7f\xfe\x97\x5f\xfe"
      "\xb6\xfc\xd7\xd7\xff\xbc\xfb\xe0\x7b\x7f\xfa\xdd\xff\xbe\x34\x97\x55\x6b"
      "\x32\x2f\x6b\x6f\xc7\x65\x7a\x96\xa6\x6f\x47\x8c\x1d\xc4\xc9\x64\x9f\xe2"
      "\x17\x7a\x11\x6c\x00\x46\xf2\x74\x6d\xd0\x15\xe1\x42\x92\x88\xf8\x60\x64"
      "\xbf\xa3\xd9\xf1\x3f\x15\x23\x31\x3a\xe8\x2a\x01\x00\x3d\x96\xa6\x53\x91"
      "\x4e\xb5\xe7\x01\x80\xab\x2e\x69\xcc\x81\x15\x92\xe9\x7c\x2e\x60\x32\x92"
      "\xa4\x58\x6c\x9e\x0b\xbc\x10\x37\x92\x72\xb5\x56\x7f\x65\xa5\xba\xb5\xb1"
      "\xdc\x9c\x2b\xbb\x15\x63\xc9\xca\x5a\xb9\x74\x2f\x9f\x2b\xbc\x15\x63\x85"
      "\x2c\x3f\x13\x11\x37\xdb\xf2\xf7\x8f\x94\xcf\x46\xc4\xf3\x11\xf1\xed\xf1"
      "\xeb\x8d\x7c\x71\xa9\x5a\x5e\x1e\xd8\x59\x0f\x00\x0c\xb7\xe7\xf2\xf1\xbf"
      "\x98\x8f\xff\xff\x1a\x3f\x1c\xff\xcf\x60\xa2\xa7\x95\x03\x00\x7a\xa7\x31"
      "\x8a\xbf\xf8\x83\x41\x57\x03\x00\xe8\x23\x57\xf1\x00\x30\x7c\xce\x31\xfe"
      "\x7f\xfe\x7e\x2f\x2b\x02\x00\xf4\x8d\xeb\x7f\x00\x18\x3e\xc6\x7f\x00\x18"
      "\x3e\xc7\xc7\xff\xf4\xec\x77\xd5\x02\x00\xde\x97\x5c\xff\x03\xc0\x50\xf9"
      "\xe2\x1b\x6f\x64\x29\xdd\xcf\xef\x7f\xbd\xfc\xe6\xf6\xd6\x7a\xf5\xcd\xbb"
      "\xcb\xa5\xda\x7a\xb1\xb2\xb5\x54\x5c\xaa\x6e\x3e\x2a\xae\x56\xab\xab\x8d"
      "\x7b\xf6\x54\x4e\x7b\xbf\x72\xb5\xfa\xe8\xfe\x7c\x6c\x3d\x9e\xae\x97\x6a"
      "\xf5\xe9\xda\xf6\xce\x42\xa5\xba\xb5\x51\x5f\x68\xdc\xd7\x7b\xa1\x34\xd6"
      "\x97\x56\x01\x00\x27\x79\xfe\xa5\xbd\x3f\x16\x22\x62\xf7\x53\xd7\x1b\x29"
      "\xda\xd6\x72\x30\x56\xc3\xd5\x96\x5c\xf4\x85\x96\x09\x81\xf7\x3d\xdf\xf3"
      "\xc3\xf0\x32\x8c\xc3\xf0\x72\x8d\x0f\x74\x58\xa2\xf7\x5d\xba\xfe\x17\xa1"
      "\x77\xba\xec\x4f\xd3\x34\xed\x52\x74\xfb\xec\xd5\x02\x7a\xe8\xce\x87\xcd"
      "\xff\xc3\xb0\x3a\x36\xff\xff\xad\xf1\xc1\x54\x04\xe8\xbb\x23\xf3\xff\xbf"
      "\x3e\xd8\x32\x31\x08\x57\x9e\xc3\x1c\x86\x57\x9a\x16\xac\xf9\x0f\x00\x43"
      "\xe6\xe4\x39\xfe\xff\xf6\xed\x3c\x04\x18\x9c\x73\x7d\xff\x7f\xad\x6d\xbb"
      "\xdb\xf7\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x30\x04\x26\x1b\xa9\x90\x14\xf3\xb5"
      "\xc0\x27\x23\x49\x8a\xc5\x88\x9b\x11\x71\x2b\xde\x3e\x78\xde\x07\x22\xe2"
      "\x0f\xe3\x63\xe3\x2b\x6b\xe5\xd2\xcc\x40\x6b\x0c\x00\xbc\x77\xc9\xdf\x0a"
      "\xf9\xfa\x5f\x77\xa6\x5e\x9e\x3c\x5a\x7a\xad\xf0\xef\xf1\xc8\x97\xfc\xfa"
      "\xc6\xf7\x1f\x7e\xe7\xf1\x62\xbd\xbe\x39\x93\xed\xff\xe7\xc1\xfe\xfa\x3b"
      "\xf9\xfe\xfb\x83\xa8\x3f\x00\x70\x9a\xd6\x38\xdd\x1a\xc7\x5b\x9e\x3d\x7d"
      "\x6b\xa9\x95\xfa\x59\x9f\xbf\x7f\xa6\xb9\xb8\x68\x16\x77\x3f\x4f\xcd\x92"
      "\xd1\x18\x6d\x3c\x4e\xc4\x58\x44\xdc\xd8\x2f\xe4\xf9\xa6\xec\x7c\x65\xe4"
      "\x12\xe2\xef\x3e\x89\x88\x17\x3b\xb5\xbf\xd0\x98\x1b\xb9\x95\xaf\x7c\x7a"
      "\x34\x7e\x16\xfb\x66\x5f\xe3\x27\xef\x8a\x9f\x34\xca\x9a\x8f\xd9\x67\xf1"
      "\xa1\x4b\xa8\x0b\x0c\x9b\xbd\xac\xff\x79\xad\xd3\xf1\x97\xc4\xed\xc6\xe3"
      "\xc4\x93\xd6\x73\xdb\x8f\xbf\x89\x23\xf9\x8b\x6a\xf5\x7f\xad\xbe\xef\x70"
      "\x1d\xe6\xe4\xa0\xff\x1b\xe9\xd0\xff\x5c\x8f\xc8\xeb\xd7\xc9\x37\x7f\xd3"
      "\x9e\xbb\xf7\xfb\xca\x7e\xd7\xf8\x4f\x22\x3e\x32\x7a\x18\x7f\xbf\xad\xff"
      "\x69\xc5\x2f\x74\xe9\x7f\x5f\xee\xf0\x7e\x9d\xfa\xe4\x1f\x7f\x75\xef\x57"
      "\xdd\xe2\xa7\x3f\x8a\xb8\x13\x9d\xe3\xb7\xc7\x9a\xae\x57\x62\xa2\xb6\xbd"
      "\x73\x77\xad\xb2\xb8\x5a\x5a\x2d\x6d\xcc\xcc\xbd\x3a\x3b\x3f\x3f\xf7\x60"
      "\x7e\x76\x7a\x65\xad\x5c\xba\xd7\xfc\xb7\x63\x8c\xff\x7c\xf7\x17\x0b\x27"
      "\xb5\xff\x46\x97\xf8\x13\xa7\xb4\xff\xe3\xdd\xde\xf4\x88\xaf\xfc\xec\xe1"
      "\x67\x3f\x7a\x42\xfc\x4f\x7e\xac\x53\xfc\x24\x5e\x38\x21\xfe\x58\x24\xf1"
      "\x89\x33\xc6\x7f\xfc\xe9\x1f\xee\x75\x2b\xcb\xe2\x2f\x77\x69\xff\x69\x3f"
      "\xff\x57\xce\x18\xff\x27\x3f\xfd\x5c\xd7\x9f\x3f\x00\xd0\x7f\xb5\xed\x9d"
      "\xf5\xc5\x72\xb9\xb4\x69\xc3\xc6\x39\x36\x0a\x57\xf5\xf7\xa7\x70\xe1\x97"
      "\xbf\x14\x97\x57\x8d\xec\xf2\x6e\xc0\x9f\xc6\x80\x3b\x26\xa0\xe7\x0e\x0f"
      "\xfa\xf3\xbf\x36\xe9\x45\x85\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x80\x63\xfa\xf1\xe7\x44\x83\x6e\x23\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x57\xd7\xff"
      "\x03\x00\x00\xff\xff\x5e\xe0\xdd\x46",
      1305));
  NONFAILING(syz_mount_image(
      /*fs=*/0x200002c0, /*dir=*/0x200000c0,
      /*flags=MS_PRIVATE|MS_POSIXACL|MS_REMOUNT*/ 0x50020, /*opts=*/0x20000300,
      /*chdir=*/0xfd, /*size=*/0x519, /*img=*/0x20001080));
}
int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x20000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x21000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  const char* reason;
  (void)reason;
  install_segv_handler();
  loop();
  return 0;
}
