// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <dirent.h>
#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/prctl.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

#ifndef __NR_mlock2
#define __NR_mlock2 325
#endif

static void sleep_ms(uint64_t ms)
{
  usleep(ms * 1000);
}

static uint64_t current_time_ms(void)
{
  struct timespec ts;
  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    exit(1);
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

static bool write_file(const char* file, const char* what, ...)
{
  char buf[1024];
  va_list args;
  va_start(args, what);
  vsnprintf(buf, sizeof(buf), what, args);
  va_end(args);
  buf[sizeof(buf) - 1] = 0;
  int len = strlen(buf);
  int fd = open(file, O_WRONLY | O_CLOEXEC);
  if (fd == -1)
    return false;
  if (write(fd, buf, len) != len) {
    int err = errno;
    close(fd);
    errno = err;
    return false;
  }
  close(fd);
  return true;
}

static void kill_and_wait(int pid, int* status)
{
  kill(-pid, SIGKILL);
  kill(pid, SIGKILL);
  for (int i = 0; i < 100; i++) {
    if (waitpid(-1, status, WNOHANG | __WALL) == pid)
      return;
    usleep(1000);
  }
  DIR* dir = opendir("/sys/fs/fuse/connections");
  if (dir) {
    for (;;) {
      struct dirent* ent = readdir(dir);
      if (!ent)
        break;
      if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0)
        continue;
      char abort[300];
      snprintf(abort, sizeof(abort), "/sys/fs/fuse/connections/%s/abort",
               ent->d_name);
      int fd = open(abort, O_WRONLY);
      if (fd == -1) {
        continue;
      }
      if (write(fd, abort, 1) < 0) {
      }
      close(fd);
    }
    closedir(dir);
  } else {
  }
  while (waitpid(-1, status, __WALL) != pid) {
  }
}

static void setup_test()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  setpgrp();
  write_file("/proc/self/oom_score_adj", "1000");
}

static void execute_one(void);

#define WAIT_FLAGS __WALL

static void loop(void)
{
  int iter = 0;
  for (;; iter++) {
    int pid = fork();
    if (pid < 0)
      exit(1);
    if (pid == 0) {
      setup_test();
      execute_one();
      exit(0);
    }
    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      if (waitpid(-1, &status, WNOHANG | WAIT_FLAGS) == pid)
        break;
      sleep_ms(1);
      if (current_time_ms() - start < 5000)
        continue;
      kill_and_wait(pid, &status);
      break;
    }
  }
}

uint64_t r[3] = {0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff};

void execute_one(void)
{
  intptr_t res = 0;
  memcpy((void*)0x20000000, "./file0\000", 8);
  res = syscall(__NR_creat, /*file=*/0x20000000ul, /*mode=*/0ul);
  if (res != -1)
    r[0] = res;
  memcpy(
      (void*)0x200005c0,
      "\x46\xf2\x5f\x54\x16\x3a\x25\xbe\x2e\x85\xbe\xe6\xfb\x6c\x07\x63\x17\x85"
      "\x77\x2d\x39\xb5\xb3\x80\x8e\xe6\x3b\xee\x55\x9d\x7b\x69\x07\x9a\x3f\x6b"
      "\xee\x66\xe2\x55\xb6\xde\x13\xd7\xd1\x21\x42\x64\xd6\xa0\xf5\x4d\x68\xa0"
      "\xf5\x9e\x5b\x00\x58\x44\xbc\xe3\x44\x61\xff\xf9\x81\x21\x2c\x41\x0c\x11"
      "\xa3\x99\xae\x09\x81\x88\xdf\x4a\xef\xc6\x38\x0c\xd0\x74\x10\x66\xff\x92"
      "\x9e\x11\xd1\x33\x3e\x2b\x32\xe3\xd4\xf2\x2b\x2a\x61\xb4\x7b\xbb\x69\x24"
      "\x88\x95\x7c\xdd\x67\x29\x79\x3c\x79\x6a\xee\x91\x76\x06\xa3\x40\x08\xdc"
      "\xf4\xa8\xf8\x72\x2a\x1a\xf6\x57\x7b\x55\xd9\xc0\xe2\xa2\x2a\x8c\xef\x6f"
      "\x40\xaf\x5c\x9e\x2e\x0d\xdb\xb0\x96\xb0\xac\x33\xf5\x78\x35\x24\xcd\x34"
      "\x77\xd9\xa4\x1e\x24\x2d\x12\x14\xd8\xd6\xe0\x41\x32\x7e\x46\x37\xd9\x81"
      "\x8a\x15\xbe\x4c\xa4\x64\x66\xf8\x03\x31\xa1\xe7\xbc\xec\xb6\xb2\xff\x7c"
      "\x1a\xe0\x86\xbc\x25\x59\x11\xcb\xe8\x5f\x09\xa7\xdd\x1f\x77\x59\x9e\xd4"
      "\x70\x48\xf5\x21\x8e\x52\xcc\x1c\x55\xbd\x56\x3f\x6a\x66\xcd\xb1\x31\x9d"
      "\x55\xb3\x14\x12\x62\xf7\x4b\x18\x70\xaf\x1f\x11\xbf\xc0\x2f\x0a\xc9\x47"
      "\xb4\xb0\x26\x79\xf8\x3d\x75\x71\xb8\xbc\x22\xf0\x0d\xf1\x8e\x05\x0c\x1e"
      "\x62\x5a\x72\x64\xfb\xba\xb1\xf1\x2b\x10\x3e\xb0\x75\x7e\xad\xcf\xbf\xc4"
      "\x11\x12\x1a\xa5\xda\xbb\xe4\xdb\xf9\x91\xcf\x6d\xe1\xb8\x84\xbd\xac\x2d"
      "\x16\x7e\x4c\x5a\xe3\x67\x96\x83\x40",
      315);
  syscall(__NR_write, /*fd=*/r[0], /*buf=*/0x200005c0ul,
          /*count=*/0xffffff22ul);
  memcpy((void*)0x20000080, "./file0\000", 8);
  res = syscall(__NR_openat, /*fd=*/0xffffff9c, /*file=*/0x20000080ul,
                /*flags=*/0ul, /*mode=*/0ul);
  if (res != -1)
    r[1] = res;
  syscall(__NR_mmap, /*addr=*/0x20ffc000ul, /*len=*/0x3000ul, /*prot=*/1ul,
          /*flags=*/0x11ul, /*fd=*/r[1], /*offset=*/0ul);
  syscall(__NR_madvise, /*addr=*/0x20ffc000ul, /*len=*/0x4000ul,
          /*advice=MADV_HWPOISON*/ 0x64ul);
  memcpy((void*)0x20000080, "./file0\000", 8);
  res = syscall(__NR_openat, /*fd=*/0xffffff9c, /*file=*/0x20000080ul,
                /*flags=O_SYNC|O_NOFOLLOW|O_DIRECT|O_CREAT|O_RDWR*/ 0x125042ul,
                /*mode=*/0ul);
  if (res != -1)
    r[2] = res;
  syscall(__NR_mmap, /*addr=*/0x20c00000ul, /*len=*/0x400000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC|0x10*/ 0x17ul,
          /*flags=MAP_FIXED|MAP_SHARED*/ 0x11ul, /*fd=*/r[2], /*offset=*/0ul);
  syscall(__NR_mlock2, /*addr=*/0x20c00000ul, /*size=*/0x400000ul,
          /*flags=*/0ul);
  syscall(__NR_mremap, /*addr=*/0x20e40000ul, /*len=*/0x3000ul,
          /*newlen=*/0x3000ul,
          /*flags=MREMAP_DONTUNMAP|MREMAP_FIXED|MREMAP_MAYMOVE*/ 7ul,
          /*newaddr=*/0x20fc6000ul);
  syscall(__NR_madvise, /*addr=*/0x20400000ul, /*len=*/0xc00000ul,
          /*advice=MADV_PAGEOUT*/ 0x15ul);
}
int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x20000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x21000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  loop();
  return 0;
}
