// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#ifndef __NR_bpf
#define __NR_bpf 321
#endif

int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x20000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x21000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);

  *(uint32_t*)0x200009c0 = 9;
  *(uint32_t*)0x200009c4 = 0xd;
  *(uint64_t*)0x200009c8 = 0x20000000;
  memcpy(
      (void*)0x20000000,
      "\x18\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x85\x10"
      "\x00\x00\x01\x00\x00\x00\x95\x00\x00\x00\x00\x00\x00\x00\x18\x02\x00\x00"
      "\x78\x6c\x6c\x25\x00\x00\x00\x00\x00\x20\x20\x20\x06\x00\x00\x00\x00\x00"
      "\x00\x00\xbd\xa2\xff\xff\x00\x00\x00\x00\x35\x01\x00\x00\xf8\xff\xe3\xff"
      "\xb5\x02\x00\x00\x08\x00\x00\x00\xb5\x03\x00\x00\x00\x00\x00\x00\x85\x00"
      "\x00\x00\x2c\x00\x00\x00\x95\x00\x00\x00\x00\x00\x00\x00",
      104);
  *(uint64_t*)0x200009d0 = 0x200002c0;
  memcpy((void*)0x200002c0, "GPL\000", 4);
  *(uint32_t*)0x200009d8 = 0;
  *(uint32_t*)0x200009dc = 0;
  *(uint64_t*)0x200009e0 = 0;
  *(uint32_t*)0x200009e8 = 0;
  *(uint32_t*)0x200009ec = 0;
  memset((void*)0x200009f0, 0, 16);
  *(uint32_t*)0x20000a00 = 0;
  *(uint32_t*)0x20000a04 = 0;
  *(uint32_t*)0x20000a08 = -1;
  *(uint32_t*)0x20000a0c = 0;
  *(uint64_t*)0x20000a10 = 0;
  *(uint32_t*)0x20000a18 = 0;
  *(uint32_t*)0x20000a1c = 0;
  *(uint64_t*)0x20000a20 = 0;
  *(uint32_t*)0x20000a28 = 0;
  *(uint32_t*)0x20000a2c = 0;
  *(uint32_t*)0x20000a30 = 0;
  *(uint32_t*)0x20000a34 = 0;
  *(uint64_t*)0x20000a38 = 0;
  *(uint64_t*)0x20000a40 = 0;
  *(uint32_t*)0x20000a48 = 0;
  *(uint32_t*)0x20000a4c = 3;
  syscall(__NR_bpf, /*cmd=*/5ul, /*arg=*/0x200009c0ul, /*size=*/0x90ul);
  return 0;
}
