// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <dirent.h>
#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <sched.h>
#include <setjmp.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/prctl.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

static __thread int clone_ongoing;
static __thread int skip_segv;
static __thread jmp_buf segv_env;

static void segv_handler(int sig, siginfo_t* info, void* ctx)
{
  if (__atomic_load_n(&clone_ongoing, __ATOMIC_RELAXED) != 0) {
    exit(sig);
  }
  uintptr_t addr = (uintptr_t)info->si_addr;
  const uintptr_t prog_start = 1 << 20;
  const uintptr_t prog_end = 100 << 20;
  int skip = __atomic_load_n(&skip_segv, __ATOMIC_RELAXED) != 0;
  int valid = addr < prog_start || addr > prog_end;
  if (skip && valid) {
    _longjmp(segv_env, 1);
  }
  exit(sig);
}

static void install_segv_handler(void)
{
  struct sigaction sa;
  memset(&sa, 0, sizeof(sa));
  sa.sa_handler = SIG_IGN;
  syscall(SYS_rt_sigaction, 0x20, &sa, NULL, 8);
  syscall(SYS_rt_sigaction, 0x21, &sa, NULL, 8);
  memset(&sa, 0, sizeof(sa));
  sa.sa_sigaction = segv_handler;
  sa.sa_flags = SA_NODEFER | SA_SIGINFO;
  sigaction(SIGSEGV, &sa, NULL);
  sigaction(SIGBUS, &sa, NULL);
}

#define NONFAILING(...)                                                        \
  ({                                                                           \
    int ok = 1;                                                                \
    __atomic_fetch_add(&skip_segv, 1, __ATOMIC_SEQ_CST);                       \
    if (_setjmp(segv_env) == 0) {                                              \
      __VA_ARGS__;                                                             \
    } else                                                                     \
      ok = 0;                                                                  \
    __atomic_fetch_sub(&skip_segv, 1, __ATOMIC_SEQ_CST);                       \
    ok;                                                                        \
  })

static void sleep_ms(uint64_t ms)
{
  usleep(ms * 1000);
}

static uint64_t current_time_ms(void)
{
  struct timespec ts;
  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    exit(1);
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

#define BITMASK(bf_off, bf_len) (((1ull << (bf_len)) - 1) << (bf_off))
#define STORE_BY_BITMASK(type, htobe, addr, val, bf_off, bf_len)               \
  *(type*)(addr) =                                                             \
      htobe((htobe(*(type*)(addr)) & ~BITMASK((bf_off), (bf_len))) |           \
            (((type)(val) << (bf_off)) & BITMASK((bf_off), (bf_len))))

static bool write_file(const char* file, const char* what, ...)
{
  char buf[1024];
  va_list args;
  va_start(args, what);
  vsnprintf(buf, sizeof(buf), what, args);
  va_end(args);
  buf[sizeof(buf) - 1] = 0;
  int len = strlen(buf);
  int fd = open(file, O_WRONLY | O_CLOEXEC);
  if (fd == -1)
    return false;
  if (write(fd, buf, len) != len) {
    int err = errno;
    close(fd);
    errno = err;
    return false;
  }
  close(fd);
  return true;
}

static void kill_and_wait(int pid, int* status)
{
  kill(-pid, SIGKILL);
  kill(pid, SIGKILL);
  for (int i = 0; i < 100; i++) {
    if (waitpid(-1, status, WNOHANG | __WALL) == pid)
      return;
    usleep(1000);
  }
  DIR* dir = opendir("/sys/fs/fuse/connections");
  if (dir) {
    for (;;) {
      struct dirent* ent = readdir(dir);
      if (!ent)
        break;
      if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0)
        continue;
      char abort[300];
      snprintf(abort, sizeof(abort), "/sys/fs/fuse/connections/%s/abort",
               ent->d_name);
      int fd = open(abort, O_WRONLY);
      if (fd == -1) {
        continue;
      }
      if (write(fd, abort, 1) < 0) {
      }
      close(fd);
    }
    closedir(dir);
  } else {
  }
  while (waitpid(-1, status, __WALL) != pid) {
  }
}

static void setup_test()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  setpgrp();
  write_file("/proc/self/oom_score_adj", "1000");
}

#define USLEEP_FORKED_CHILD (3 * 50 * 1000)

static long handle_clone_ret(long ret)
{
  if (ret != 0) {
    __atomic_store_n(&clone_ongoing, 0, __ATOMIC_RELAXED);
    return ret;
  }
  usleep(USLEEP_FORKED_CHILD);
  syscall(__NR_exit, 0);
  while (1) {
  }
}

static long syz_clone(volatile long flags, volatile long stack,
                      volatile long stack_len, volatile long ptid,
                      volatile long ctid, volatile long tls)
{
  long sp = (stack + stack_len) & ~15;
  __atomic_store_n(&clone_ongoing, 1, __ATOMIC_RELAXED);
  long ret = (long)syscall(__NR_clone, flags & ~CLONE_VM, sp, ptid, ctid, tls);
  return handle_clone_ret(ret);
}

static void execute_one(void);

#define WAIT_FLAGS __WALL

static void loop(void)
{
  int iter = 0;
  for (;; iter++) {
    int pid = fork();
    if (pid < 0)
      exit(1);
    if (pid == 0) {
      setup_test();
      execute_one();
      exit(0);
    }
    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      sleep_ms(10);
      if (waitpid(-1, &status, WNOHANG | WAIT_FLAGS) == pid)
        break;
      if (current_time_ms() - start < 5000)
        continue;
      kill_and_wait(pid, &status);
      break;
    }
  }
}

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};

void execute_one(void)
{
  intptr_t res = 0;
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  NONFAILING(memcpy(
      (void*)0x20000000,
      "\xf2\x45\xaa\xfd\x70\x37\xdb\x9b\x01\x18\x39\x8a\x52\x0c\xfe\x77", 16));
  NONFAILING(*(uint64_t*)0x20000010 = 0);
  NONFAILING(*(uint64_t*)0x20000018 = 0);
  NONFAILING(*(uint64_t*)0x20000020 = 3);
  NONFAILING(*(uint32_t*)0x20000028 = 0x10000c);
  NONFAILING(*(uint64_t*)0x20000030 = 0x80000000000000);
  NONFAILING(*(uint32_t*)0x20000038 = 4);
  NONFAILING(*(uint64_t*)0x20000040 = 9);
  NONFAILING(*(uint64_t*)0x20000048 = 0xffffffffffffff80);
  NONFAILING(*(uint64_t*)0x20000050 = 9);
  NONFAILING(*(uint64_t*)0x20000058 = 1);
  NONFAILING(*(uint64_t*)0x20000060 = 4);
  NONFAILING(*(uint64_t*)0x20000068 = 0xa);
  NONFAILING(*(uint64_t*)0x20000070 = 7);
  NONFAILING(*(uint64_t*)0x20000078 = 0xfffffffffffffffd);
  NONFAILING(*(uint64_t*)0x20000080 = 1);
  NONFAILING(*(uint64_t*)0x20000088 = 0x3c);
  NONFAILING(*(uint64_t*)0x20000090 = 7);
  NONFAILING(*(uint64_t*)0x20000098 = 6);
  NONFAILING(*(uint64_t*)0x200000a0 = 0xba0);
  NONFAILING(*(uint64_t*)0x200000a8 = 4);
  NONFAILING(*(uint64_t*)0x200000b0 = 0x4f6edb63);
  NONFAILING(*(uint64_t*)0x200000b8 = 0xef);
  NONFAILING(*(uint64_t*)0x200000c0 = 5);
  syscall(__NR_ioctl, /*fd=*/-1, /*cmd=*/0xc0c89425, /*arg=*/0x20000000ul);
  NONFAILING(memcpy((void*)0x20000080, "/dev/iommu\000", 11));
  res = syscall(__NR_openat, /*fd=*/0xffffffffffffff9cul, /*file=*/0x20000080ul,
                /*flags=*/0, /*mode=*/0);
  if (res != -1)
    r[0] = res;
  NONFAILING(*(uint32_t*)0x20000000 = 0xc);
  NONFAILING(*(uint32_t*)0x20000004 = 0);
  syscall(__NR_ioctl, /*fd=*/r[0], /*cmd=*/0x3b81, /*arg=*/0x20000000ul);
  NONFAILING(*(uint64_t*)0x20000000 = 4);
  syscall(__NR_signalfd4, /*fd=*/-1, /*mask=*/0x20000000ul, /*size=*/8ul,
          /*flags=SFD_CLOEXEC|SFD_NONBLOCK*/ 0x80800ul);
  syscall(__NR_mprotect, /*addr=*/0x20000000ul, /*len=*/0x4000ul,
          /*prot=PROT_READ|PROT_EXEC*/ 5ul);
  NONFAILING(*(uint32_t*)0x20000000 = 5);
  NONFAILING(*(uint32_t*)0x20000004 = 0x80);
  NONFAILING(*(uint8_t*)0x20000008 = 1);
  NONFAILING(*(uint8_t*)0x20000009 = 0x6b);
  NONFAILING(*(uint8_t*)0x2000000a = 0x4a);
  NONFAILING(*(uint8_t*)0x2000000b = 1);
  NONFAILING(*(uint32_t*)0x2000000c = 0);
  NONFAILING(*(uint64_t*)0x20000010 = 0xfff);
  NONFAILING(*(uint64_t*)0x20000018 = 0x24608);
  NONFAILING(*(uint64_t*)0x20000020 = 7);
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 0, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 1, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 2, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 1, 3, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 1, 4, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 5, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 1, 6, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 7, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 8, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 1, 9, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 10, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 1, 11, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 12, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 13, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 14, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 3, 15, 2));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 17, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 18, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 19, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 1, 20, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 21, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 1, 22, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 23, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 1, 24, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 25, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 1, 26, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 1, 27, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 28, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 29, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 30, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 31, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 32, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 1, 33, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 1, 34, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 35, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 36, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 37, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 38, 26));
  NONFAILING(*(uint32_t*)0x20000030 = 4);
  NONFAILING(*(uint32_t*)0x20000034 = 4);
  NONFAILING(*(uint64_t*)0x20000038 = 0xffffffff85ce8000);
  NONFAILING(*(uint64_t*)0x20000040 = 0x401);
  NONFAILING(*(uint64_t*)0x20000048 = 0x12500);
  NONFAILING(*(uint64_t*)0x20000050 = 6);
  NONFAILING(*(uint32_t*)0x20000058 = 6);
  NONFAILING(*(uint32_t*)0x2000005c = 7);
  NONFAILING(*(uint64_t*)0x20000060 = 9);
  NONFAILING(*(uint32_t*)0x20000068 = 0x7e);
  NONFAILING(*(uint16_t*)0x2000006c = 0xa2f4);
  NONFAILING(*(uint16_t*)0x2000006e = 0);
  NONFAILING(*(uint32_t*)0x20000070 = 2);
  NONFAILING(*(uint32_t*)0x20000074 = 0);
  NONFAILING(*(uint64_t*)0x20000078 = 4);
  syscall(__NR_perf_event_open, /*attr=*/0x20000000ul, /*pid=*/0, /*cpu=*/0ul,
          /*group=*/-1, /*flags=*/0ul);
  syscall(__NR_close, /*fd=*/-1);
  NONFAILING(*(uint32_t*)0x20000000 = 5);
  NONFAILING(*(uint32_t*)0x20000004 = 0x80);
  NONFAILING(*(uint8_t*)0x20000008 = 0);
  NONFAILING(*(uint8_t*)0x20000009 = 0x6b);
  NONFAILING(*(uint8_t*)0x2000000a = 8);
  NONFAILING(*(uint8_t*)0x2000000b = 4);
  NONFAILING(*(uint32_t*)0x2000000c = 0);
  NONFAILING(*(uint64_t*)0x20000010 = 0x10000);
  NONFAILING(*(uint64_t*)0x20000018 = 0);
  NONFAILING(*(uint64_t*)0x20000020 = 0x17);
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 0, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 1, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 2, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 1, 3, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 1, 4, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 5, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 1, 6, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 7, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 8, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 1, 9, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 10, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 1, 11, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 12, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 13, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 14, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 3, 15, 2));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 17, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 18, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 19, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 1, 20, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 21, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 1, 22, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 23, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 1, 24, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 25, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 1, 26, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 1, 27, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 28, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 29, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 30, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 31, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 32, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 1, 33, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 1, 34, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 35, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 36, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 37, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 38, 26));
  NONFAILING(*(uint32_t*)0x20000030 = 0x4004);
  NONFAILING(*(uint32_t*)0x20000034 = 2);
  NONFAILING(*(uint64_t*)0x20000038 = 0x10001);
  NONFAILING(*(uint64_t*)0x20000040 = 0xc527);
  NONFAILING(*(uint64_t*)0x20000048 = 0x12b8a);
  NONFAILING(*(uint64_t*)0x20000050 = 2);
  NONFAILING(*(uint32_t*)0x20000058 = 0x106);
  NONFAILING(*(uint32_t*)0x2000005c = 9);
  NONFAILING(*(uint64_t*)0x20000060 = 2);
  NONFAILING(*(uint32_t*)0x20000068 = 2);
  NONFAILING(*(uint16_t*)0x2000006c = 0xa2f4);
  NONFAILING(*(uint16_t*)0x2000006e = 0);
  NONFAILING(*(uint32_t*)0x20000070 = 4);
  NONFAILING(*(uint32_t*)0x20000074 = 0);
  NONFAILING(*(uint64_t*)0x20000078 = 0xffffffff00000000);
  res = syscall(__NR_perf_event_open, /*attr=*/0x20000000ul, /*pid=*/0,
                /*cpu=*/0x3fffffffful, /*group=*/-1,
                /*flags=PERF_FLAG_FD_CLOEXEC*/ 8ul);
  if (res != -1)
    r[1] = res;
  syscall(__NR_mmap, /*addr=*/0x20ffd000ul, /*len=*/0x3000ul,
          /*prot=PROT_GROWSDOWN|PROT_WRITE|PROT_READ*/ 0x1000003ul,
          /*flags=MAP_FIXED|MAP_SHARED*/ 0x11ul, /*fd=*/r[1], /*offset=*/0ul);
  NONFAILING(syz_clone(/*flags=CLONE_SETTLS|CLONE_PTRACE*/ 0x82000, /*stack=*/0,
                       /*stack_len=*/0, /*parentid=*/0, /*childtid=*/0,
                       /*tls=*/0));
}
int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x20000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x21000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  const char* reason;
  (void)reason;
  install_segv_handler();
  loop();
  return 0;
}
