// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#ifndef __NR_bpf
#define __NR_bpf 321
#endif
#ifndef __NR_seccomp
#define __NR_seccomp 317
#endif

#define BITMASK(bf_off, bf_len) (((1ull << (bf_len)) - 1) << (bf_off))
#define STORE_BY_BITMASK(type, htobe, addr, val, bf_off, bf_len)               \
  *(type*)(addr) =                                                             \
      htobe((htobe(*(type*)(addr)) & ~BITMASK((bf_off), (bf_len))) |           \
            (((type)(val) << (bf_off)) & BITMASK((bf_off), (bf_len))))

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x20000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x21000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  intptr_t res = 0;
  syscall(__NR_unshare,
          /*flags=CLONE_NEWNET|CLONE_FS|CLONE_FILES*/ 0x40000600ul);
  *(uint32_t*)0x20000680 = 0x20;
  *(uint32_t*)0x20000684 = 4;
  *(uint64_t*)0x20000688 = 0x20000200;
  memcpy((void*)0x20000200,
         "\x18\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x85"
         "\x00\x00\x00\x08\x00\x00\x00\x95",
         25);
  *(uint64_t*)0x20000690 = 0x20000300;
  memcpy((void*)0x20000300, "syzkaller\000", 10);
  *(uint32_t*)0x20000698 = 0;
  *(uint32_t*)0x2000069c = 0;
  *(uint64_t*)0x200006a0 = 0;
  *(uint32_t*)0x200006a8 = 0;
  *(uint32_t*)0x200006ac = 0;
  memset((void*)0x200006b0, 0, 16);
  *(uint32_t*)0x200006c0 = 0;
  *(uint32_t*)0x200006c4 = 0x2d;
  *(uint32_t*)0x200006c8 = -1;
  *(uint32_t*)0x200006cc = 0;
  *(uint64_t*)0x200006d0 = 0;
  *(uint32_t*)0x200006d8 = 0;
  *(uint32_t*)0x200006dc = 0;
  *(uint64_t*)0x200006e0 = 0;
  *(uint32_t*)0x200006e8 = 0;
  *(uint32_t*)0x200006ec = 0;
  *(uint32_t*)0x200006f0 = 0;
  *(uint32_t*)0x200006f4 = 0;
  *(uint64_t*)0x200006f8 = 0;
  *(uint64_t*)0x20000700 = 0;
  *(uint32_t*)0x20000708 = 0;
  *(uint32_t*)0x2000070c = 0;
  res = syscall(__NR_bpf, /*cmd=*/5ul, /*arg=*/0x20000680ul, /*size=*/0x90ul);
  if (res != -1)
    r[0] = res;
  *(uint32_t*)0x20001340 = r[0];
  *(uint32_t*)0x20001344 = 0;
  *(uint32_t*)0x20001348 = 0x2d;
  *(uint32_t*)0x2000134c = 0;
  *(uint32_t*)0x20001350 = 0xa;
  *(uint32_t*)0x20001354 = 1;
  *(uint32_t*)0x20001358 = 0;
  *(uint32_t*)0x2000135c = 0;
  syscall(__NR_bpf, /*cmd=*/0x1cul, /*arg=*/0x20001340ul, /*size=*/0x40ul);
  *(uint32_t*)0x20000000 = 2;
  *(uint32_t*)0x20000004 = 0x80;
  *(uint8_t*)0x20000008 = 0x5b;
  *(uint8_t*)0x20000009 = 1;
  *(uint8_t*)0x2000000a = 0;
  *(uint8_t*)0x2000000b = 0;
  *(uint32_t*)0x2000000c = 0;
  *(uint64_t*)0x20000010 = 0;
  *(uint64_t*)0x20000018 = 0;
  *(uint64_t*)0x20000020 = 0;
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 0, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 1, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 2, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 3, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 4, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 5, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 6, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 7, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 8, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 9, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 10, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 11, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 12, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 13, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 14, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 15, 2);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 17, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 18, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 19, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 20, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 21, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 22, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 23, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 24, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 25, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 26, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 27, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 28, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 29, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 30, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 31, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 32, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 33, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 34, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 35, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 36, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 37, 1);
  STORE_BY_BITMASK(uint64_t, , 0x20000028, 0, 38, 26);
  *(uint32_t*)0x20000030 = 0;
  *(uint32_t*)0x20000034 = 0;
  *(uint64_t*)0x20000038 = 0;
  *(uint64_t*)0x20000040 = 0;
  *(uint64_t*)0x20000048 = 0;
  *(uint64_t*)0x20000050 = 0;
  *(uint32_t*)0x20000058 = 0;
  *(uint32_t*)0x2000005c = 0;
  *(uint64_t*)0x20000060 = 0;
  *(uint32_t*)0x20000068 = 0;
  *(uint16_t*)0x2000006c = 0;
  *(uint16_t*)0x2000006e = 0;
  *(uint32_t*)0x20000070 = 0;
  *(uint32_t*)0x20000074 = 0;
  *(uint64_t*)0x20000078 = 0;
  syscall(__NR_perf_event_open, /*attr=*/0x20000000ul, /*pid=*/0, /*cpu=*/0ul,
          /*group=*/-1, /*flags=*/0ul);
  syscall(__NR_seccomp, /*op=*/0ul, /*flags=*/0ul, /*arg=*/0ul);
  return 0;
}
