// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffffffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200000000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200001000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  const char* reason;
  (void)reason;
  intptr_t res = 0;
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  //  openat arguments: [
  //    fd: fd_dir (resource)
  //    file: ptr[in, buffer] {
  //      buffer: {2e 2f 66 69 6c 65 31 00} (length 0x8)
  //    }
  //    flags: open_flags = 0x42 (4 bytes)
  //    mode: open_mode = 0x0 (2 bytes)
  //  ]
  //  returns fd
  memcpy((void*)0x200000000040, "./file1\000", 8);
  syscall(__NR_openat, /*fd=*/0xffffff9c, /*file=*/0x200000000040ul,
          /*flags=O_CREAT|O_RDWR*/ 0x42, /*mode=*/0);
  //  openat$fuse arguments: [
  //    fd: const = 0xffffffffffffff9c (8 bytes)
  //    file: ptr[in, buffer] {
  //      buffer: {2f 64 65 76 2f 66 75 73 65 00} (length 0xa)
  //    }
  //    flags: const = 0x2 (4 bytes)
  //    mode: const = 0x0 (2 bytes)
  //  ]
  //  returns fd_fuse
  memcpy((void*)0x200000000180, "/dev/fuse\000", 10);
  res = syscall(__NR_openat, /*fd=*/0xffffffffffffff9cul,
                /*file=*/0x200000000180ul, /*flags=*/2, /*mode=*/0);
  if (res != -1)
    r[0] = res;
  //  close arguments: [
  //    fd: fd (resource)
  //  ]
  syscall(__NR_close, /*fd=*/4);
  //  mount$fuse arguments: [
  //    src: const = 0x0 (8 bytes)
  //    dst: ptr[in, buffer] {
  //      buffer: {2e 2f 66 69 6c 65 31 00} (length 0x8)
  //    }
  //    type: ptr[in, buffer] {
  //      buffer: {66 75 73 65 00} (length 0x5)
  //    }
  //    flags: mount_flags = 0x0 (8 bytes)
  //    opts: ptr[inout, array[ANYUNION]] {
  //      array[ANYUNION] {
  //        union ANYUNION {
  //          ANYBLOB: buffer: {66 64 3d} (length 0x3)
  //        }
  //        union ANYUNION {
  //          ANYRESHEX: ANYRES64 (resource)
  //        }
  //        union ANYUNION {
  //          ANYBLOB: buffer: {2c 72 6f 6f 74 6d 6f 64 65 3d 30 30 30 30 30 30
  //          30 30 30 30 30 30 30 30 30 30 30 31 30 30 30 30 30 2c 75 73 65 72
  //          5f 69 64 3d} (length 0x2a)
  //        }
  //        union ANYUNION {
  //          ANYRESDEC: ANYRES64 (resource)
  //        }
  //        union ANYUNION {
  //          ANYBLOB: buffer: {} (length 0x0)
  //        }
  //        union ANYUNION {
  //          ANYRESDEC: ANYRES64 (resource)
  //        }
  //      }
  //    }
  //  ]
  memcpy((void*)0x2000000020c0, "./file1\000", 8);
  memcpy((void*)0x200000002100, "fuse\000", 5);
  memcpy((void*)0x200000000080, "fd=", 3);
  sprintf((char*)0x200000000083, "0x%016llx", (long long)r[0]);
  memcpy((void*)0x200000000095,
         ",rootmode=00000000000000000100000,user_id=", 42);
  sprintf((char*)0x2000000000bf, "%020llu", (long long)0);
  sprintf((char*)0x2000000000d3, "%020llu", (long long)0);
  syscall(__NR_mount, /*src=*/0ul, /*dst=*/0x2000000020c0ul,
          /*type=*/0x200000002100ul, /*flags=*/0ul, /*opts=*/0x200000000080ul);
  return 0;
}
